import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SkillCat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{ background:"url('bg.svg')",backgroundRepeat:"no-repeat",backgroundSize:"cover" }} className="overflow-x-hidden">{children}</body>
    </html>
  );
}
